name: Event einreichen
description: Veranstaltung rund um FOSS in Baden‑Württemberg melden
title: "[Title] - City"
labels: ["event:submitted"]

body:
  - type: input
    id: title
    attributes:
      label: Title
      description: Titel (de)
    validations:
      required: true
      
  - type: dropdown
    id: event-category
    attributes:
      label: Event-Kategorie
      description: Zu welcher Kategorie gehört das Event? (Wichtig für die Filtermöglichkeit im Kalender.)
      options:
        - Community Event
        - Hackathon
        - Project Event
        - Science Event
        - Business Event
        - Sonstige (bitte im Beschreibungstext näher erläutern)
      default: 0 # Wählt 'Community Event' als Standard
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Kurzbeschreibung (de)
    validations:
      required: true

  - type: input
    id: date
    attributes:
      label: Date
      description: "Datum (Format: YYYY-MM-DD)"
      placeholder: "2025-12-20"
    validations:
      required: true

  - type: input
    id: time
    attributes:
      label: Time
      description: "Startzeit oder Zeitspanne (z. B. 18:00 oder 18:00–20:00)"
      placeholder: "18:00–20:00"
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      description: Ort/Adresse oder Online‑Link
    validations:
      required: true

  - type: input
    id: city
    attributes:
      label: City
      description: Stadt
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: URL
      description: Webseite/Anmeldung
      placeholder: "https://example.org/anmeldung"
    validations:
      required: true
      

